#!/bin/bash
#
# ipmasq.ip-down   Reinitializes the ipmasq settings when PPP goes down
#
# v1.0	19 July 1998
#####

test -x /usr/sbin/ipmasq || exit 0

if [ -e /etc/ipmasq/ppp ]; then
    /usr/sbin/ipmasq
fi

