#!/bin/sh
#
# ipmasq.init	Set up IP Masquerading for Debian systems
#
#		v3.0 19 July 1998

test -x /usr/sbin/ipmasq || exit 0

case $1 in
start|restart|force-reload)
	# Display 'whaddamidoing?' prompt
	echo -n "Initializing IP Masquerading..."

	# Setup ipmasq
	/usr/sbin/ipmasq

	# Display 'whaddamidoing?' prompt
	echo "done."
	;;
stop)
	# Display 'whaddamidoing?' prompt
	echo -n "Disabling IP Masquerading..."
		
	# Setup ipmasq
	/usr/sbin/ipmasq --rules /etc/ipmasq/ipmasq-down
				
	# Display 'whaddamidoing?' prompt
	echo "done."
	;;
*)
	echo "Usage /etc/init.d/ipmasq {start|stop|force-reload|restart}"
	exit 1
esac

