#!/bin/sh
#
# default-if	Determines the default interface
#
# v1.0	19 July 1998
# v1.1  10 Feb 1999
# v2.0  2004-01-04T16:29:38 CET Osamu Aoki
#####

export LC_ALL="C"
export LANG="C"
export LANGUAGE="C"

( /sbin/route -n | sed -n -e '/^0\.0\.0\.0 /s/.* \([^ ]*\)$/\1/p' | sort -u ) 2>/dev/null
true
