#!/bin/sh
#
# enumerate-if	Enumerates all of the currently active interfaces
#
# v1.0	19 July 1998
# v2.0  2004-01-04T16:29:38 CET Osamu Aoki
#####

export LC_ALL="C"
export LANG="C"
export LANGUAGE="C"

( /sbin/ifconfig | sed -n -e '/^[a-z]/s/^\([^ ]*\) .*$/\1/p' | sort -u ) 2>/dev/null
true
